=== CCMi-FIT/ds-km/datamodel-v1-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "title": "chapter",
    "properties": {
	"chapterid": {
	    "type": "integer"
	},
	"namespace": {
	    "type": "string"
	},
	"formatversion": {
	    "type": "integer"
	},
	"title": {
	    "type": "string"
	},
	"text": {
	    "type": "string"
	},
	"questions": {
	    "type": "array",
	    "items": {
		"type": "object",
		"title": "question",
		"properties": {
		    "questionid": {
			"type": "integer"
		    },
		    "references": {
			"type": "array",
			"items": {
			    "type": "object",
			    "title": "reference",
			    "properties": {
				"type": { "type": "string" }
			    },
			    "required": ["type"]
			}
		    },
		    "type": {
			"type": "string"
		    },
		    "title": {
			"type": "string"		  
		    },
		    "answers": {
			"type": "array",
			"items": {
			    "type": "object",
			    "title": "answer",
			    "properties": {
				"id": {
				    "type": "integer"
				},
				"label": {
				    "type": "string"
				},
				"responsetype": {
				    "type": "string"
				}
			    },
			    "required": [
				"id",
				"label",
				"responsetype"
			    ]
			}
		    }
		},
		"required": [
		    "questionid"
		]
	    }
	}
    },
    "required": [
	"chapterid",
	"namespace",
	"formatversion",
	"questions"
    ]
}

=== CCMi-FIT/ds-km/datamodel/core.d/chapter1.json
{
    "chapterid": 1,
    "namespace": "core",
    "formatversion": 1,
    "title": "Design of experiment",
    "text": "Before you decide to embark on any new study, it is nowadays good practice to consider all options to keep the data generation part of your study as limited as possible. It is not because we can generate massive amounts of data that we always need to do so. Creating data with public money is bringing with it the responsibility to treat those data well and (if potentially useful) make them available for re-use by others.",
    "questions" :
    [
	{
	    "questionid": 1, "bookreference": "1.1", "type": "choice",
	    "title": "Is there any pre-existing data?",
	    "text": "Are there any data sets available in the world that are relevant to your planned research?",
	    "answers": 
	    [ 
		{
		    "id": 0, "label": "No", "responsetype": "advice",
		    "text": "You know that this is very unlikely? This question is not only about data sets that are similar to what you want to determine yourself, but also reference data or data that should be mined from the existing literature. Further, it is very likely that you will refer to related data, e.g. other databases where you usually \"quickly look something up\", but that could maybe be properly integrated, especially if you need to do such lookups multiple times."
		},
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 2, "bookreference": "1.2", "type": "choice",
	    "precondition": { "questionid": 1, "answerid": 1 },
	    "title": "Will you be using any pre-existing data (including other people's data)?",
	    "text": "Will you be referring to any earlier measured data, reference data, or data that should be mined from existing literature? Your own data as well as data from others?",
	    "answers": 
	    [
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup"}
	    ]
	},
	{
	    "questionid": 3, "bookreference": "1.3", "type": "list",
	    "precondition": { "questionid": 2, "answerid": 1 },
	    "title": "What reference data will you use?",
	    "text": "Much of todays data is used in comparison with reference data. A genome for instance is compared with a reference genome to identify genomic variants. If you use reference data, there are several other issues that you should consider. What are the reference data sets that you will use?"
	},
	{
	    "questionid": 4, "bookreference": "1.4", "type": "choice",
	    "precondition": { "questionid": 3 },
	    "title": "Where is it available?",
	    "text": "Do you know where the reference data is available, what the conditions for use are, and how to reference it?",
	    "answers": 
	    [
		{    "id": 0, "label": "No", "responsetype": "advice", "text": "Figure this out quickly!" },
		{    "id": 1, "label": "Yes", "responsetype": "ok" } 
	    ] 
	},
	{
	    "questionid": 5, "bookreference": "1.5", "type": "choice",
	    "precondition": { "questionid": 3 },
	    "title": "In what format is the reference data available?",
	    "text": "Do you know the data format of the reference data? Is this suitable for your work? Does it need to be converted?",
	    "answers": 
	    [
		{    "id": 0, "label": "I can directly use it", "responsetype": "ok" },
		{    "id": 1, "label": "I need to convert it before using", "responsetype": "ok" } 
	    ] 
	},
	{
	    "questionid": 6, "bookreference": "1.6", "type": "choice",
	    "precondition": { "questionid": 3 },
	    "title": "Is the reference data resource versioned?",
	    "text": "Many reference data sets evolve over time. If the reference data set changes, this may affect your results. If different versions of a reference data set exist, you need to establish your \"version policy\".",
	    "answers": 
	    [
		{    "id": 0, "label": "No", "responsetype": "ok" },
		{    "id": 1, "label": "Yes", "responsetype": "followup" } 
	    ] 
	},
	{
	    "questionid": 7, "bookreference": "1.7", "type": "text",
	    "precondition": { "questionid": 6, "answerid": 1 },
	    "title": "Which version will you use?",
	    "text": "If there are different versions available, you have to decide with all project partners together which version you will be using. Probably you will go for the latest release as of the date of the start of your research project. However, if you have other data from older projects that need to be merged, you may need to consider using the same release you used for a previous project."
	},
	{
	    "questionid": 8, "bookreference": "1.7", "type": "choice",
	    "precondition": { "questionid": 6, "answerid": 1 },
	    "title": "Will you change version if it updates?",
	    "text": "If the reference changes while you are working on your research project, you need to decide whether you will follow these changes. Most likely that will mean that you have to do some analyses again, so you will need to make sure enough resources are available to do so. You can decide to stay with the version that you started with; this can have the disadvantage that you will not benefit from added information or added consistency.",
	    "answers": 
	    [
		{    "id": 0, "label": "Will stay with the old version", "responsetype": "followup" },
		{    "id": 1, "label": "New analyses will be done with the new version", "responsetype": "ok" },
		{    "id": 2, "label": "All analyses will be redone with the new version", "responsetype": "ok" } 
	    ] 
	},
	{
	    "questionid": 9, "bookreference": "1.7", "type": "list",
	    "precondition": { "questionid": 2, "answerid": 1 },
	    "title": "What existing non-reference data sets will you use?",
	    "text": "Even if you will be producing your own data, you often will also be relying on existing data sets. You may need to integrate your new data with an existing data set or retrieve additional information from related data bases. Will you be doing such things?"
	},
	{
	    "questionid": 29, "bookrefererence": "1.12", "type": "choice",
	    "title": "Will reference data be created?",
	    "answers": 
	    [
		{   "id": 0, "label": "No", "responsetype": "ok"},
		{   "id": 1, "label": "Yes", "responsetype": "followup"}
	    ]
	},
	{
	    "questionid": 33, "bookreference": "1.13", "type": "choice",
	    "title": "Will you be storing samples?",
	    "answers": 
	    [
		{   "id": 0, "label": "No", "responsetype": "ok"},
		{   "id": 1, "label": "Yes", "responsetype": "followup"}
	    ]
	},
	{
	    "questionid": 38, "bookreference": "1.14", "type": "choice",
	    "title": "Will you be collecting experimental data?",
	    "answers": 
	    [
		{   "id": 0, "label": "No", "responsetype": "ok"},
		{   "id": 1, "label": "Yes", "responsetype": "followup"}
	    ]
	}
    ]
}

=== CCMi-FIT/ds-km/datamodel/core.d/chapter4.json
{
    "chapterid": 4,
    "namespace": "core",
    "formatversion": 1,
    "title": "Data processing and curation",
    "questions" :
    [
	{
	    "questionid": 1, "type": "choice",
	    "title": "Workflow development",
	    "text": "It is likely that you will be developing or modifying the workflow for data processing. There are a lot of aspects of this workflow that can play a role in your data management, such as the use of an existing work flow engine, the use of existing software vs development of new components, and whether every run needs human intervention or whether all data processing can be run in bulk once the work flow has been defined.",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Taken care of", "responsetype": "ok" },
		{   "id": 1, "label": "Drill deeper", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 2, "type": "choice",
	    "title": "How will you make sure to know what exactly has been run?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Taken care of", "responsetype": "ok" },
		{   "id": 1, "label": "Drill deeper", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 3, "type": "choice",
	    "title": "How will you validate the integrity of the results?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Taken care of", "responsetype": "ok" },
		{   "id": 1, "label": "Drill deeper", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 4, "type": "choice",
	    "title": "Do you have a contingency plan?",
	    "text": "What will you do if the compute facility is down?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Wait", "responsetype": "ok" },
		{   "id": 1, "label": "We have an alternative", "responsetype": "ok" }
	    ]
	}
    ]
}

=== CCMi-FIT/ds-km/datamodel/core.d/chapter3.json
{
    "chapterid": 3,
    "namespace": "core",
    "formatversion": 1,
    "title": "Data Capture (the equipment phase)",
    "questions" :
    [
	{
	    "questionid": 1, "type": "choice",
	    "title": "Who will do the measurements?",
	    "text": "Are there easily accessible specialized service providers for data capture?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "In the project", "responsetype": "ok" },
		{   "id": 1, "label": "External party", "responsetype": "advice", "text": "consider making them partner in the project" }
	    ]
	},
	{
	    "questionid": 2, "type": "choice",
	    "title": "Is special care needed to get the raw data ready for processing?",
	    "text": "Where does the data come from? And who will need it? Sometimes the raw data is measured somewhere else than where the primary processing is taking place. In such cases the ingestion of the primary data may take special planning.",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 3, "type": "choice",
	    "title": "Do you have any non-equipment data capture?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 4, "type": "choice",
	    "title": "Is there a data integration tool that can handle and combine all the data types you are dealing with in your project?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "followup" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	}
    ]
}

=== CCMi-FIT/ds-km/datamodel/local/lifesciences/chapter1.json
{
    "chapterid": 6,
    "namespace": "lifesciences",
    "formatversion": 1,
    "questions" :
    [
	{
	    "questionid": 42, "type": "option",
	    "precondition": { "questionid": 2, "namespace": "core", "answerid": 1 },
	    "title": "Will you couple existing (biobank) data sets?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 43, "type": "option",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "Will you use deterministic couplings?",
	    "text": "Data sets that have exactly identical fields that are well filled can be coupled using deterministic methods. Will you be using such methods?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "ok" }
	    ]
	},
	{
	    "questionid": 44, "type": "text",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "Will you be using a trusted third party for coupling?",
	    "text": "What will be the procedure that is followed? Where will what data be sent? Did a legal advisor look at the procedures?"
	},
	{
	    "questionid": 45, "type": "option",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "Is consent available for the couplings?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "ok" }
	    ]
	},
	{
	    "questionid": 46, "type": "text",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "How will you check whether your coupled data are representative of your goal population?",
	    "text": "Sometimes, through the nature of the data sets that are coupled, the coupled set is no longer representative for the whole population (e.g. some fields may only have been filled for people with high blood pressure). This can disturb your research if undetected. How will you make sure this is not happening?"
	},
	{
	    "questionid": 47, "type": "option",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "What is the goal of the coupling?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "More data about the same subjects (intersection)", "responsetype": "ok" },
		{   "id": 1, "label": "Enlarging the group of subjects (union)", "responsetype": "ok" }
	    ]
	},
	{
	    "questionid": 48, "type": "text",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "What variable(s) will you be using for the coupling?"
	},
	{
	    "questionid": 49, "type": "option",
	    "precondition": { "questionid": 42, "answerid": 1 },
	    "title": "Will you use probabilistic couplings?",
	    "text": "Data sets that have similar but not identical fields or with identical fields that are not consistently filled can be coupled using probabilistic methods. Will you be using such methods?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "ok" }
	    ]
	}
    ]
}

=== CCMi-FIT/ds-km/datamodel/core.d/chapter7.json
{
    "chapterid": 7,
    "namespace": "core",
    "formatversion": 1,
    "title": "Information and insight",
    "questions" :
    [
	{
	    "questionid": 1, "type": "choice",
	    "title": "Will you be working with the philosophy 'as open as possible' for your data?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No", "responsetype": "advice", "text": "You will need to explain!" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 2, "type": "choice",
	    "title": " Are there legal reasons why (some of your) data can not be completely open?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" , "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 3, "type": "choice",
	    "title": " Are there business reasons why (some of your) data can not be completely open?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" , "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 4, "type": "choice",
	    "title": "Where will you make your data available?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Skip" , "responsetype": "ok" },
		{   "id": 1, "label": "Drill Deeper", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 5, "type": "choice",
	    "title": "Did you work out the financial aspects of making the data available?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Skip" , "responsetype": "ok" },
		{   "id": 1, "label": "Drill Deeper", "responsetype": "followup" }
	    ]
	},
	{
	    "questionid": 6, "type": "choice",
	    "title": "Will you be archiving data?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" , "responsetype": "ok" },
		{   "id": 1, "label": "Yes", "responsetype": "followup" }
	    ]
	}
    ]
}
